# Numpy Exercises 2

In [1]:
import numpy as np

import matplotlib.pyplot as plt
import random # Thư viện built-in của Python 

**Question 1**

Search for the duplicate entries (2nd occurrence onwards) in the given numpy array and mark them as `True`. First time occurrences should be `False` \
Input: `[0 0 3 0 2 4 2 2 2 2]` \
Correct Output: `[False  True False  True False False  True  True  True  True]`

In [12]:
#Init array
np.random.seed(100)
a = np.random.randint(0, 5, 10)
print('Array: ', a)
#TODO
result = np.zeros_like(a, dtype=bool)
values, indices, occurrence_count = np.unique(a, return_inverse=True, return_counts=True)
duplicate_values = values[occurrence_count > 1]

for val in duplicate_values:
    val_positions = np.where(a == val)[0]
    result[val_positions[1:]] = True

print(result)

Array:  [0 0 3 0 2 4 2 2 2 2]
[False  True False  True False False  True  True  True  True]


**Question 2**

Return all items in array `a` that not in array `b` \
Input: \
`a` = `[1,2,3,4,5]` \
`b` = `[5,6,7,8,9]` \
Output: \
`[1,2,3,4]`

In [3]:
a = np.random.choice(range(10), 7, replace=False)
b = np.random.choice(range(10), 7, replace=False)
print(a,b)
#TODO
print(np.setdiff1d(a, b))

[5 9 7 2 6 3 4] [0 7 1 8 5 4 3]
[2 6 9]


**Question 3**

Given a vector `a`, build a new vector with 2 consecutive zeros interleaved between each value. \
Input: \
`a` = `[4, 3, 4, 9, 8]` \
Output: \
`[4. 0. 0. 3. 0. 0. 4. 0. 0. 9. 0. 0. 8.]`

In [16]:
a = np.random.randint(1, 10, 5)
#TODO
def add_double_zeros(a):
    final_len = len(a)*3 - 2
    result = np.zeros(final_len)
    result[::3] = a
    return result
print(add_double_zeros(a))

[2. 0. 0. 2. 0. 0. 8. 0. 0. 8. 0. 0. 1.]


---
*For the next few questions we will work with `Iris Dataset`*

In [17]:
iris_1d = np.genfromtxt('Data/Iris.csv', delimiter=',', skip_header=1, dtype=None,encoding=None)
iris_2d = np.array([row.tolist()[:4] for row in iris_1d])
iris_2d

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

**Question 4**\
Filter the rows of iris_2d that has `petallength` (3rd column) > 1.5 and `sepallength` (1st column) < 5.0

In [19]:
sepal_length, sepal_width, petal_length, petal_width = map(np.array, zip(*iris_2d))
mask = (petal_length > 1.5) & (sepal_length < 5.0)
np.where(mask)

(array([ 11,  24,  29,  30,  57, 106], dtype=int64),)

**Question 5**\
Add a new text column to `iris_2d`, which based on the petal length (3rd) column, such that if petal length is: \
- `Less than 3` --> 'small'
- `3-5` --> 'medium'
- `>=5` --> 'large'

In [20]:
def classify_petal_size(len):
    if len < 3:
        return 'small'
    elif len < 5:
        return 'medium'
    return 'large'

size_classifications = np.array([classify_petal_size(length) for length in petal_length])
iris_2d = np.concatenate((iris_2d, size_classifications.reshape(-1, 1)), axis=1)

**Question 6**\
Find the value of second longest `petallength` of species `setosa`

In [ ]:
species = np.genfromtxt("Data/Iris.csv", delimiter=",", usecols=4, skip_header=1, dtype=str)

# Lấy ra những giá trị phân biệt cho length của cá thể setosa
setosa_mask = species == 'Iris-setosa'
setosa_petals = list(set(petal_length[setosa_mask])) 

# Sort và lấy giá trị petal length lớn thứ 2
second_longest = np.sort(setosa_petals)[-2]
second_longest

1.7